### ISSUE TITLE
static config format incompatible with OTP

### ISSUE THREAD

**Issue by leoliu** [g-andrade/aequitas#2]
The following format is incompatible. Key must be an atom; see `application_controller:check_para/2` for details.

```
{aequitas,
  [{{category, http_requests},
    [{max_window_duration, {seconds,10}} % Override default 5s to 10s
    ]},

   {{category, rare_ftp_requests},
    [{max_window_size, 100} % Only track up to the last 100 acceptances
    ]}
  ]}
```

**Comment by g-andrade** [comment]
Ahh, indeed..  I abused an undocumented feature without noticing. It was bound to break some day. Test cases should cover this too.. 
I'll try to look into it soon.

**Comment by g-andrade** [comment]
It's not crashing in either OTP 21.0 or OTP 21.1, which means it's not (yet) broken in practice.

But I'll change the spec anyway (while keeping retro-compatibility for the time being.)

**Comment by leoliu** [comment]
Did you try it in a release with the configuration in `sys.config`? That's how I got a crash.

**Comment by g-andrade** [comment]
Indeed! I stand corrected. It appears `:check_para/2` is executed during release launches but not in other situations (e.g. common tests, or in rebar3 shell.)

I've added a new test case for covering release launching and will use this to ensure the fix works and there are no future regressions.

**Comment by g-andrade** [comment]
Fixed in version 1.1.0 (both tagged in repo and published to hex.pm.)

**Comment by g-andrade** [comment]
The release-compatible static configuration format is as follows:

```erlang
% ...
 {aequitas,
  [{categories,
   #{ http_requests =>
        [{max_window_duration, {seconds,10}}] % Override default 5s to 10s

      rare_ftp_requests =>
        [{max_window_size, 100}] % Only track up to the last 100 acceptances
   }}
  ]}
% ...
```

**Comment by leoliu** [comment]
I just upgraded to 1.1.0 and it is working nicely ;)
